/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PageLoaderRouteImport } from './routes/page-loader'
import { Route as publicRouteRouteImport } from './routes/(public)/route'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as adminRouteRouteImport } from './routes/(admin)/route'
import { Route as publicIndexRouteImport } from './routes/(public)/index'
import { Route as publicDemoRouteImport } from './routes/(public)/demo'
import { Route as publicCheckoutRouteImport } from './routes/(public)/checkout'
import { Route as publicCartRouteImport } from './routes/(public)/cart'
import { Route as authRegisterRouteImport } from './routes/(auth)/register'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as publicProductsIndexRouteImport } from './routes/(public)/products/index'
import { Route as adminAdminIndexRouteImport } from './routes/(admin)/admin/index'
import { Route as publicProductsSlugRouteImport } from './routes/(public)/products/$slug'
import { Route as adminAdminDashboardRouteImport } from './routes/(admin)/admin/dashboard'
import { Route as adminAdminUsersIndexRouteImport } from './routes/(admin)/admin/users/index'
import { Route as adminAdminPromotionalBannersIndexRouteImport } from './routes/(admin)/admin/promotional-banners/index'
import { Route as adminAdminProductsIndexRouteImport } from './routes/(admin)/admin/products/index'
import { Route as adminAdminOrdersIndexRouteImport } from './routes/(admin)/admin/orders/index'
import { Route as adminAdminPromotionalBannersCreateRouteImport } from './routes/(admin)/admin/promotional-banners/create'
import { Route as adminAdminProductsCreateRouteImport } from './routes/(admin)/admin/products/create'
import { Route as adminAdminOrdersIdRouteImport } from './routes/(admin)/admin/orders/$id'
import { Route as adminAdminProductsIdEditRouteImport } from './routes/(admin)/admin/products/$id.edit'

const PageLoaderRoute = PageLoaderRouteImport.update({
  id: '/page-loader',
  path: '/page-loader',
  getParentRoute: () => rootRouteImport,
} as any)
const publicRouteRoute = publicRouteRouteImport.update({
  id: '/(public)',
  getParentRoute: () => rootRouteImport,
} as any)
const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const adminRouteRoute = adminRouteRouteImport.update({
  id: '/(admin)',
  getParentRoute: () => rootRouteImport,
} as any)
const publicIndexRoute = publicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => publicRouteRoute,
} as any)
const publicDemoRoute = publicDemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => publicRouteRoute,
} as any)
const publicCheckoutRoute = publicCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => publicRouteRoute,
} as any)
const publicCartRoute = publicCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => publicRouteRoute,
} as any)
const authRegisterRoute = authRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => authRouteRoute,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => authRouteRoute,
} as any)
const publicProductsIndexRoute = publicProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => publicRouteRoute,
} as any)
const adminAdminIndexRoute = adminAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => adminRouteRoute,
} as any)
const publicProductsSlugRoute = publicProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => publicRouteRoute,
} as any)
const adminAdminDashboardRoute = adminAdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => adminRouteRoute,
} as any)
const adminAdminUsersIndexRoute = adminAdminUsersIndexRouteImport.update({
  id: '/admin/users/',
  path: '/admin/users/',
  getParentRoute: () => adminRouteRoute,
} as any)
const adminAdminPromotionalBannersIndexRoute =
  adminAdminPromotionalBannersIndexRouteImport.update({
    id: '/admin/promotional-banners/',
    path: '/admin/promotional-banners/',
    getParentRoute: () => adminRouteRoute,
  } as any)
const adminAdminProductsIndexRoute = adminAdminProductsIndexRouteImport.update({
  id: '/admin/products/',
  path: '/admin/products/',
  getParentRoute: () => adminRouteRoute,
} as any)
const adminAdminOrdersIndexRoute = adminAdminOrdersIndexRouteImport.update({
  id: '/admin/orders/',
  path: '/admin/orders/',
  getParentRoute: () => adminRouteRoute,
} as any)
const adminAdminPromotionalBannersCreateRoute =
  adminAdminPromotionalBannersCreateRouteImport.update({
    id: '/admin/promotional-banners/create',
    path: '/admin/promotional-banners/create',
    getParentRoute: () => adminRouteRoute,
  } as any)
const adminAdminProductsCreateRoute =
  adminAdminProductsCreateRouteImport.update({
    id: '/admin/products/create',
    path: '/admin/products/create',
    getParentRoute: () => adminRouteRoute,
  } as any)
const adminAdminOrdersIdRoute = adminAdminOrdersIdRouteImport.update({
  id: '/admin/orders/$id',
  path: '/admin/orders/$id',
  getParentRoute: () => adminRouteRoute,
} as any)
const adminAdminProductsIdEditRoute =
  adminAdminProductsIdEditRouteImport.update({
    id: '/admin/products/$id/edit',
    path: '/admin/products/$id/edit',
    getParentRoute: () => adminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/page-loader': typeof PageLoaderRoute
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/cart': typeof publicCartRoute
  '/checkout': typeof publicCheckoutRoute
  '/demo': typeof publicDemoRoute
  '/': typeof publicIndexRoute
  '/admin/dashboard': typeof adminAdminDashboardRoute
  '/products/$slug': typeof publicProductsSlugRoute
  '/admin/': typeof adminAdminIndexRoute
  '/products/': typeof publicProductsIndexRoute
  '/admin/orders/$id': typeof adminAdminOrdersIdRoute
  '/admin/products/create': typeof adminAdminProductsCreateRoute
  '/admin/promotional-banners/create': typeof adminAdminPromotionalBannersCreateRoute
  '/admin/orders/': typeof adminAdminOrdersIndexRoute
  '/admin/products/': typeof adminAdminProductsIndexRoute
  '/admin/promotional-banners/': typeof adminAdminPromotionalBannersIndexRoute
  '/admin/users/': typeof adminAdminUsersIndexRoute
  '/admin/products/$id/edit': typeof adminAdminProductsIdEditRoute
}
export interface FileRoutesByTo {
  '/page-loader': typeof PageLoaderRoute
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/cart': typeof publicCartRoute
  '/checkout': typeof publicCheckoutRoute
  '/demo': typeof publicDemoRoute
  '/': typeof publicIndexRoute
  '/admin/dashboard': typeof adminAdminDashboardRoute
  '/products/$slug': typeof publicProductsSlugRoute
  '/admin': typeof adminAdminIndexRoute
  '/products': typeof publicProductsIndexRoute
  '/admin/orders/$id': typeof adminAdminOrdersIdRoute
  '/admin/products/create': typeof adminAdminProductsCreateRoute
  '/admin/promotional-banners/create': typeof adminAdminPromotionalBannersCreateRoute
  '/admin/orders': typeof adminAdminOrdersIndexRoute
  '/admin/products': typeof adminAdminProductsIndexRoute
  '/admin/promotional-banners': typeof adminAdminPromotionalBannersIndexRoute
  '/admin/users': typeof adminAdminUsersIndexRoute
  '/admin/products/$id/edit': typeof adminAdminProductsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(admin)': typeof adminRouteRouteWithChildren
  '/(auth)': typeof authRouteRouteWithChildren
  '/(public)': typeof publicRouteRouteWithChildren
  '/page-loader': typeof PageLoaderRoute
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/register': typeof authRegisterRoute
  '/(public)/cart': typeof publicCartRoute
  '/(public)/checkout': typeof publicCheckoutRoute
  '/(public)/demo': typeof publicDemoRoute
  '/(public)/': typeof publicIndexRoute
  '/(admin)/admin/dashboard': typeof adminAdminDashboardRoute
  '/(public)/products/$slug': typeof publicProductsSlugRoute
  '/(admin)/admin/': typeof adminAdminIndexRoute
  '/(public)/products/': typeof publicProductsIndexRoute
  '/(admin)/admin/orders/$id': typeof adminAdminOrdersIdRoute
  '/(admin)/admin/products/create': typeof adminAdminProductsCreateRoute
  '/(admin)/admin/promotional-banners/create': typeof adminAdminPromotionalBannersCreateRoute
  '/(admin)/admin/orders/': typeof adminAdminOrdersIndexRoute
  '/(admin)/admin/products/': typeof adminAdminProductsIndexRoute
  '/(admin)/admin/promotional-banners/': typeof adminAdminPromotionalBannersIndexRoute
  '/(admin)/admin/users/': typeof adminAdminUsersIndexRoute
  '/(admin)/admin/products/$id/edit': typeof adminAdminProductsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/page-loader'
    | '/login'
    | '/register'
    | '/cart'
    | '/checkout'
    | '/demo'
    | '/'
    | '/admin/dashboard'
    | '/products/$slug'
    | '/admin/'
    | '/products/'
    | '/admin/orders/$id'
    | '/admin/products/create'
    | '/admin/promotional-banners/create'
    | '/admin/orders/'
    | '/admin/products/'
    | '/admin/promotional-banners/'
    | '/admin/users/'
    | '/admin/products/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/page-loader'
    | '/login'
    | '/register'
    | '/cart'
    | '/checkout'
    | '/demo'
    | '/'
    | '/admin/dashboard'
    | '/products/$slug'
    | '/admin'
    | '/products'
    | '/admin/orders/$id'
    | '/admin/products/create'
    | '/admin/promotional-banners/create'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/promotional-banners'
    | '/admin/users'
    | '/admin/products/$id/edit'
  id:
    | '__root__'
    | '/(admin)'
    | '/(auth)'
    | '/(public)'
    | '/page-loader'
    | '/(auth)/login'
    | '/(auth)/register'
    | '/(public)/cart'
    | '/(public)/checkout'
    | '/(public)/demo'
    | '/(public)/'
    | '/(admin)/admin/dashboard'
    | '/(public)/products/$slug'
    | '/(admin)/admin/'
    | '/(public)/products/'
    | '/(admin)/admin/orders/$id'
    | '/(admin)/admin/products/create'
    | '/(admin)/admin/promotional-banners/create'
    | '/(admin)/admin/orders/'
    | '/(admin)/admin/products/'
    | '/(admin)/admin/promotional-banners/'
    | '/(admin)/admin/users/'
    | '/(admin)/admin/products/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  adminRouteRoute: typeof adminRouteRouteWithChildren
  authRouteRoute: typeof authRouteRouteWithChildren
  publicRouteRoute: typeof publicRouteRouteWithChildren
  PageLoaderRoute: typeof PageLoaderRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/page-loader': {
      id: '/page-loader'
      path: '/page-loader'
      fullPath: '/page-loader'
      preLoaderRoute: typeof PageLoaderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)': {
      id: '/(public)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof publicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(admin)': {
      id: '/(admin)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof adminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/': {
      id: '/(public)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicIndexRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/demo': {
      id: '/(public)/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof publicDemoRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/checkout': {
      id: '/(public)/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof publicCheckoutRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/cart': {
      id: '/(public)/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof publicCartRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(auth)/register': {
      id: '/(auth)/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof authRegisterRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(public)/products/': {
      id: '/(public)/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof publicProductsIndexRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(admin)/admin/': {
      id: '/(admin)/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof adminAdminIndexRouteImport
      parentRoute: typeof adminRouteRoute
    }
    '/(public)/products/$slug': {
      id: '/(public)/products/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof publicProductsSlugRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(admin)/admin/dashboard': {
      id: '/(admin)/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof adminAdminDashboardRouteImport
      parentRoute: typeof adminRouteRoute
    }
    '/(admin)/admin/users/': {
      id: '/(admin)/admin/users/'
      path: '/admin/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof adminAdminUsersIndexRouteImport
      parentRoute: typeof adminRouteRoute
    }
    '/(admin)/admin/promotional-banners/': {
      id: '/(admin)/admin/promotional-banners/'
      path: '/admin/promotional-banners'
      fullPath: '/admin/promotional-banners/'
      preLoaderRoute: typeof adminAdminPromotionalBannersIndexRouteImport
      parentRoute: typeof adminRouteRoute
    }
    '/(admin)/admin/products/': {
      id: '/(admin)/admin/products/'
      path: '/admin/products'
      fullPath: '/admin/products/'
      preLoaderRoute: typeof adminAdminProductsIndexRouteImport
      parentRoute: typeof adminRouteRoute
    }
    '/(admin)/admin/orders/': {
      id: '/(admin)/admin/orders/'
      path: '/admin/orders'
      fullPath: '/admin/orders/'
      preLoaderRoute: typeof adminAdminOrdersIndexRouteImport
      parentRoute: typeof adminRouteRoute
    }
    '/(admin)/admin/promotional-banners/create': {
      id: '/(admin)/admin/promotional-banners/create'
      path: '/admin/promotional-banners/create'
      fullPath: '/admin/promotional-banners/create'
      preLoaderRoute: typeof adminAdminPromotionalBannersCreateRouteImport
      parentRoute: typeof adminRouteRoute
    }
    '/(admin)/admin/products/create': {
      id: '/(admin)/admin/products/create'
      path: '/admin/products/create'
      fullPath: '/admin/products/create'
      preLoaderRoute: typeof adminAdminProductsCreateRouteImport
      parentRoute: typeof adminRouteRoute
    }
    '/(admin)/admin/orders/$id': {
      id: '/(admin)/admin/orders/$id'
      path: '/admin/orders/$id'
      fullPath: '/admin/orders/$id'
      preLoaderRoute: typeof adminAdminOrdersIdRouteImport
      parentRoute: typeof adminRouteRoute
    }
    '/(admin)/admin/products/$id/edit': {
      id: '/(admin)/admin/products/$id/edit'
      path: '/admin/products/$id/edit'
      fullPath: '/admin/products/$id/edit'
      preLoaderRoute: typeof adminAdminProductsIdEditRouteImport
      parentRoute: typeof adminRouteRoute
    }
  }
}

interface adminRouteRouteChildren {
  adminAdminDashboardRoute: typeof adminAdminDashboardRoute
  adminAdminIndexRoute: typeof adminAdminIndexRoute
  adminAdminOrdersIdRoute: typeof adminAdminOrdersIdRoute
  adminAdminProductsCreateRoute: typeof adminAdminProductsCreateRoute
  adminAdminPromotionalBannersCreateRoute: typeof adminAdminPromotionalBannersCreateRoute
  adminAdminOrdersIndexRoute: typeof adminAdminOrdersIndexRoute
  adminAdminProductsIndexRoute: typeof adminAdminProductsIndexRoute
  adminAdminPromotionalBannersIndexRoute: typeof adminAdminPromotionalBannersIndexRoute
  adminAdminUsersIndexRoute: typeof adminAdminUsersIndexRoute
  adminAdminProductsIdEditRoute: typeof adminAdminProductsIdEditRoute
}

const adminRouteRouteChildren: adminRouteRouteChildren = {
  adminAdminDashboardRoute: adminAdminDashboardRoute,
  adminAdminIndexRoute: adminAdminIndexRoute,
  adminAdminOrdersIdRoute: adminAdminOrdersIdRoute,
  adminAdminProductsCreateRoute: adminAdminProductsCreateRoute,
  adminAdminPromotionalBannersCreateRoute:
    adminAdminPromotionalBannersCreateRoute,
  adminAdminOrdersIndexRoute: adminAdminOrdersIndexRoute,
  adminAdminProductsIndexRoute: adminAdminProductsIndexRoute,
  adminAdminPromotionalBannersIndexRoute:
    adminAdminPromotionalBannersIndexRoute,
  adminAdminUsersIndexRoute: adminAdminUsersIndexRoute,
  adminAdminProductsIdEditRoute: adminAdminProductsIdEditRoute,
}

const adminRouteRouteWithChildren = adminRouteRoute._addFileChildren(
  adminRouteRouteChildren,
)

interface authRouteRouteChildren {
  authLoginRoute: typeof authLoginRoute
  authRegisterRoute: typeof authRegisterRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authLoginRoute: authLoginRoute,
  authRegisterRoute: authRegisterRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

interface publicRouteRouteChildren {
  publicCartRoute: typeof publicCartRoute
  publicCheckoutRoute: typeof publicCheckoutRoute
  publicDemoRoute: typeof publicDemoRoute
  publicIndexRoute: typeof publicIndexRoute
  publicProductsSlugRoute: typeof publicProductsSlugRoute
  publicProductsIndexRoute: typeof publicProductsIndexRoute
}

const publicRouteRouteChildren: publicRouteRouteChildren = {
  publicCartRoute: publicCartRoute,
  publicCheckoutRoute: publicCheckoutRoute,
  publicDemoRoute: publicDemoRoute,
  publicIndexRoute: publicIndexRoute,
  publicProductsSlugRoute: publicProductsSlugRoute,
  publicProductsIndexRoute: publicProductsIndexRoute,
}

const publicRouteRouteWithChildren = publicRouteRoute._addFileChildren(
  publicRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  adminRouteRoute: adminRouteRouteWithChildren,
  authRouteRoute: authRouteRouteWithChildren,
  publicRouteRoute: publicRouteRouteWithChildren,
  PageLoaderRoute: PageLoaderRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
